import type { Plugin } from "@opencode-ai/plugin"

// Generated by SB from the user-global five-tool manifest.
// The placeholder is replaced with the absolute manifest-selected RTK binary.
const RTK_COMMAND = "__SB_RTK_COMMAND__"

export const RtkOpenCodePlugin: Plugin = async ({ $ }) => {
  return {
    "tool.execute.before": async (input, output) => {
      const tool = String(input?.tool ?? "").toLowerCase()
      if (tool !== "bash" && tool !== "shell") return
      const args = output?.args
      if (!args || typeof args !== "object") return

      const command = (args as Record<string, unknown>).command
      if (typeof command !== "string" || !command) return
      if (/^\s*rtk(?:\s|$)/.test(command)) return

      try {
        const result = await $`${RTK_COMMAND} rewrite ${command}`.quiet().nothrow()
        const rewritten = String(result.stdout).trim()
        if (result.exitCode === 0 && rewritten && rewritten !== command) {
          ;(args as Record<string, unknown>).command = rewritten
        }
      } catch {
        // RTK rewrite failed — pass through unchanged.
      }
    },
  }
}
