#!/usr/bin/env bash
set -euo pipefail
trap 'printf "{\"hookSpecificOutput\":{\"message\":\"⚠️ pr-traceability: hook error — check jq/input format\"}}" ; exit 0' ERR

# PostToolUse hook (matcher: Bash)
# After `gh pr create` runs, appends spec traceability block to the PR description
# and updates SPEC.md Implementations section with the PR URL.
# Reads session context from ~/.claude/.silver-bullet/spec-session (written at session start).

# Security: restrict file creation permissions (user-only)
umask 0077

# jq is required for JSON parsing
if ! command -v jq >/dev/null 2>&1; then
  printf '{"hookSpecificOutput":{"message":"⚠️ Silver Bullet hooks require jq. Install: brew install jq (macOS) / apt install jq (Linux)"}}'
  exit 0
fi

# Resolve gh CLI at runtime (CR-01 fix: cross-platform)
GH_BIN=$(command -v gh || command -v /opt/homebrew/bin/gh || command -v /usr/local/bin/gh || true)
if [[ -z "$GH_BIN" ]]; then
  printf '{"hookSpecificOutput":{"message":"⚠️ pr-traceability: gh CLI not found — traceability block skipped."}}'
  exit 0
fi

# Read JSON from stdin
input=$(cat)

# Extract command from Bash tool input
cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // ""')

# Only trigger on actual `gh pr create` commands
if ! printf '%s' "$cmd" | grep -qE '\bgh pr create\b'; then
  exit 0
fi

# Read spec-session file — if missing, no spec session, exit silently
SB_STATE_DIR="${HOME}/.claude/.silver-bullet"
spec_session_file="${SB_STATE_DIR}/spec-session"

if [[ ! -f "$spec_session_file" ]]; then
  exit 0
fi

# Extract spec-version and jira-id with validation (CR-03 fix)
spec_version=$(grep '^spec-version=' "$spec_session_file" | cut -d'=' -f2 | grep -E '^[0-9]+(\.[0-9]+)*$' || echo "unknown")
jira_id=$(grep '^jira-id=' "$spec_session_file" | cut -d'=' -f2 | grep -E '^[A-Z]+-[0-9]+$' || echo "")

# Read WARN findings from VALIDATION.md if it exists
warn_items=""
if [[ -f ".planning/VALIDATION.md" ]]; then
  warn_items=$(grep 'FINDING \[WARN\]' .planning/VALIDATION.md || true)
fi

# Get the current PR URL (just created by the gh pr create command)
pr_url=$("$GH_BIN" pr view --json url --jq '.url' 2>/dev/null || true)

if [[ -z "$pr_url" ]]; then
  printf '{"hookSpecificOutput":{"message":"⚠️ pr-traceability: Could not determine PR URL — traceability block skipped."}}'
  exit 0
fi

# Read existing PR body — do NOT overwrite (Pitfall 4: append only)
existing_body=$("$GH_BIN" pr view --json body --jq '.body' 2>/dev/null || true)

# Build traceability block safely — no heredoc expansion (BFIX-02)
traceability_block=$(printf '\n---\n## Spec Traceability (auto-generated by Silver Bullet)\n- Spec: .planning/SPEC.md (v%s)\n- JIRA: %s\n- Requirements covered: see SPEC.md ## Acceptance Criteria\n\n### Deferred items (WARN findings from silver-validate)\n%s' "$spec_version" "${jira_id:-n/a}" "${warn_items:-None}")

# Append traceability block to existing PR body
new_body="${existing_body}${traceability_block}"

# Write to temp file and update PR
tmpfile=$(mktemp)
printf '%s' "$new_body" > "$tmpfile"
"$GH_BIN" pr edit "$pr_url" --body-file "$tmpfile" 2>/dev/null || true
rm -f "$tmpfile"

# TRAC-04: Update SPEC.md Implementations section with PR URL
SPEC=".planning/SPEC.md"
if [[ -f "$SPEC" ]]; then
  today=$(date '+%Y-%m-%d')
  entry="- PR: ${pr_url} | Date: ${today} | Spec-version: ${spec_version}"

  # Insert entry after the <!-- Populated automatically comment (idempotent — skip if already inserted)
  if ! grep -qF "$pr_url" "$SPEC" 2>/dev/null; then
    ENTRY="$entry" awk 'BEGIN{e=ENVIRON["ENTRY"]} /<!-- Populated automatically/ { print; print e; next } { print }' "$SPEC" > "${SPEC}.tmp" && mv "${SPEC}.tmp" "$SPEC"

    git add "$SPEC" 2>/dev/null || true
    git commit -m "trace: link PR to SPEC.md v${spec_version}" 2>/dev/null || true
  fi
fi

msg=$(printf 'Spec traceability added to PR description.' | jq -Rs '.')
printf '{"hookSpecificOutput":{"message":%s}}' "$msg"

exit 0
