#!/usr/bin/env bash
set -euo pipefail
trap 'exit 0' ERR

# PostToolUse hook (matcher: Bash)
# After `gh pr create` runs, appends spec traceability block to the PR description
# and updates SPEC.md Implementations section with the PR URL.
# Reads session context from ~/.claude/.silver-bullet/spec-session (written at session start).

# Security: restrict file creation permissions (user-only)
umask 0077

# jq is required for JSON parsing
if ! command -v jq >/dev/null 2>&1; then
  printf '{"hookSpecificOutput":{"message":"⚠️ Silver Bullet hooks require jq. Install: brew install jq (macOS) / apt install jq (Linux)"}}'
  exit 0
fi

# Read JSON from stdin
input=$(cat)

# Extract command from Bash tool input
cmd=$(printf '%s' "$input" | jq -r '.tool_input.command // ""')

# Only trigger on actual `gh pr create` commands
if ! printf '%s' "$cmd" | grep -qE '\bgh pr create\b'; then
  exit 0
fi

# Read spec-session file — if missing, no spec session, exit silently
SB_STATE_DIR="${HOME}/.claude/.silver-bullet"
spec_session_file="${SB_STATE_DIR}/spec-session"

if [[ ! -f "$spec_session_file" ]]; then
  exit 0
fi

# Extract spec-version and jira-id from spec-session file
spec_version=$(grep '^spec-version=' "$spec_session_file" | cut -d'=' -f2 || true)
jira_id=$(grep '^jira-id=' "$spec_session_file" | cut -d'=' -f2 || true)

# Read WARN findings from VALIDATION.md if it exists
warn_items=""
if [[ -f ".planning/VALIDATION.md" ]]; then
  warn_items=$(grep 'FINDING \[WARN\]' .planning/VALIDATION.md || true)
fi

# Get the current PR URL (just created by the gh pr create command)
pr_url=$(/opt/homebrew/bin/gh pr view --json url --jq '.url' 2>/dev/null || true)

if [[ -z "$pr_url" ]]; then
  printf '{"hookSpecificOutput":{"message":"⚠️ pr-traceability: Could not determine PR URL — traceability block skipped."}}'
  exit 0
fi

# Read existing PR body — do NOT overwrite (Pitfall 4: append only)
existing_body=$(/opt/homebrew/bin/gh pr view --json body --jq '.body' 2>/dev/null || true)

# Build traceability block
traceability_block=$(cat <<TRACE

---
## Spec Traceability (auto-generated by Silver Bullet)
- Spec: .planning/SPEC.md (v${spec_version:-unknown})
- JIRA: ${jira_id:-n/a}
- Requirements covered: see SPEC.md ## Acceptance Criteria

### Deferred items (WARN findings from silver-validate)
${warn_items:-None}
TRACE
)

# Append traceability block to existing PR body
new_body="${existing_body}${traceability_block}"

# Write to temp file and update PR
tmpfile=$(mktemp)
printf '%s' "$new_body" > "$tmpfile"
/opt/homebrew/bin/gh pr edit "$pr_url" --body-file "$tmpfile" 2>/dev/null || true
rm -f "$tmpfile"

# TRAC-04: Update SPEC.md Implementations section with PR URL
SPEC=".planning/SPEC.md"
if [[ -f "$SPEC" ]]; then
  today=$(date '+%Y-%m-%d')
  entry="- PR: ${pr_url} | Date: ${today} | Spec-version: ${spec_version:-unknown}"

  # Insert entry after the <!-- Populated automatically comment in ## Implementations section
  awk -v entry="$entry" '
    /<!-- Populated automatically/ { print; print entry; next }
    { print }
  ' "$SPEC" > "${SPEC}.tmp" && mv "${SPEC}.tmp" "$SPEC"

  git add "$SPEC" 2>/dev/null || true
  git commit --no-verify -m "trace: link PR to SPEC.md v${spec_version:-unknown}" 2>/dev/null || true
fi

printf '{"hookSpecificOutput":{"message":"Spec traceability added to PR description."}}'

exit 0
